services:
  db:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_DB: shelterapplicationdb
      POSTGRES_USER: shelteruser
      POSTGRES_PASSWORD: shelterpassword
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg: